language: julia

env:
  - IMAGE=texlive-julia-minimal

os: linux

dist: trusty

sudo: required

services:
  - docker

notifications:
  email: false

script:
  - pwd
  - ls
  - build-script.sh
  - test-script.sh

after_success:
  - push-script.sh
